const config = require('../config.js');

/**
 * List all of a Square user's transactions
 * @Deprecated
 * @param  {[type]}   req  [description]
 * @param  {[type]}   res  [description]
 * @param  {Function} next [description]
 * @return {[type]}        [description]
 */
exports.transactions = function(req, res, next) {
  const user = req.user;
  config.square.listTransactions(user.square_id, (transactions, err) => {
    if (err) {
      console.log(err)
      return next(err)
    }
    return res.json(transactions);
  });
}

/**
 * Query Square API for discounts matching those generated by FRx. If any are
 * found, mark the prescription as filled and store the associated transaction
 * in the FRx database.
 * @param  {[type]}   req  [description]
 * @param  {[type]}   res  [description]
 * @param  {Function} next [description]
 * @return {[type]}        [description]
 */
exports.handle_daily_transactions = function(req, res, next) {
    var end = new Date();
    end.setHours(0,0,0,0);
    var begin = end.getDate()-1;

    config.square.listPayments({"begin_time": begin, "end_time": end}, (payments, err) {
        if (err) {
            return next(err);
        }
        payments.foreach((payment) => {
            if (payment.itemizations.discounts) {
                discounts = payment.itemizations.discounts;
                discounts.foreach((discount) => {
                    // TODO - Find the discount in the database.
                    // If it exists, mark it as filled, save the transaction in
                    // the transactions collection. Otherwise ignore.
                });
            }
        });
    });
}
